### ISSUE TITLE
gender_verb function

### ISSUE THREAD

**Issue by kenalba** [dhmit/gender_analysis#114]
We already have a gender_adjective function and we have parts of speech - adding a function that figures out what verbs male and female pronouns are doing is an easy extension to create that adds a lot of functionality.

**Comment by samimak37** [comment]
If we want to start adding different types of speech, I wonder if we should consider putting all of the `gender_{part of speech}` functions into one function, that maybe accepts a parameter that defines what part of speech the user wants (i.e. a user can input `"v"` to get verbs, `"adj"` to get adjectives, etc.)? I haven't looked into this a whole lot, so it may be out of scope and/or harder than is reasonable at this point, but it's something to consider.

**Comment by MBJean** [comment]
If this issue originally conceived of expanding on the functions in `gender_analysis`, then the issue as outlined is resolved (started in PR #149 and concluded in PR #159). There's also the functionality in `dependency_parsing`, which uses a dependency tree to more accurately determine the relationship between parts of speech and gender identifiers, but that does contain functions for both adjectives and verbs. It seems to me like this issue is probably resolved, with the possibility of creating a new issue that expands on or abstracts the capabilities of the `depdency_parsing` module. I'll close this, but we can discuss in our Friday meeting.
