### ISSUE TITLE
Determine the ideal user interface

### ISSUE THREAD

**Issue by MBJean** [dhmit/gender_analysis#157]
# Overview
I'd like to spend some time thinking about the current interface we provide users for performing the various pieces of functionality of the GATK.

## Some mock usage code
These are notes. I'm recording them here as we go:

```
# Version where analyzer classes subclass a base analyzer class
from text_analysis_toolkit import GenderPronounAnalyzer
pronoun_analyzer = GenderPronounAnalyzer('filepath', csv_path='whatever')
gender_pronoun_results = pronoun_analyzer.by_date(# args, author_gender='male')
ngram_results = pronoun_analyzer.get_ngrams(length=2, sort=True)
```

```
# Version where there's just one analyzer class (probably not feasible)
from text_analysis_toolkit import Analyzer
analyzer = Analyzer('filepath', csv_path='whatever')
ngram_results = analyzer.get_ngrams(length=2, sort=True)
gender_pronoun_results = analyzer.gender_pronouns_by_date(# args, author_gender='male')
```

```
# What happens if the user wants to mutate the underlying corpus?
import text_analysis_toolkit as tatk
analyzer = tatk.GenderPronounAnalyzer(filepath, metadata_csv)
author_gender_frequencies = analyzer.count_authors_by_gender()
analysizer.corpus = analyzer.corpus.filter_by_gender('male')
male_author_male_adjectives = analyzer.find_male_adjectives()
```

```
class BaseAnalyzer:
    """
    Implements common textual analysis methods. Assumes documents are in English.
    """
    def get_ngrams(self):
        # do some stuff with self.corpus, but don't mutate it

class LatinAnalyzer(BaseAnalyzer):
    """
    Extends basic CLTK functionality. Overrides English-specific methods from BaseAnalyzer
    by using CLTK instead of NLTK in many places.
    """

class GenderPronounAnalyzer(BaseAnalyzer):
    """
    Implements gender-specific analysis methods
    """
```

**Comment by ryaanahmed** [comment]
The first version here (where analyzer classes subclass a base analyzer class) seems like the right path to me. Some things for us to think about:
- What happens if a user mutates the corpus attached to an Analyzer directly? This could be a problem if any Analyzer caches results, which seems likely. I don't think we need to resolve this in a first pass of this design.
- `Corpus` and `Document` currently implement methods that should probably be moved to the `BaseAnalyzer` class in this design, leaving those two classes basically responsible for data and metadata storage, filtering, etc. (e.g., `Corpus.get_wordcount_counter` should move to `BaseAnalyzer` but `Corpus.subcorpus` is exactly where it should be).
- What goes in `BaseAnalyzer`? Is this even an analyzer anyone uses, or is just where we stick utility methods like the basic initialization routine, etc.?

**Comment by kenalba** [comment]
I'd encourage us to think, here, about processing load! Initializing our Analyzer functions on medium-to-large corpora takes a really long time, so I think we want to do that as little as possible. For example, the `GenderPronounAnalyzer` function needs to be initialized for each part-of-speech set; if I want to look for verbs but have initialized based on adjectives, e.g., I have to initialize twice.

**Comment by MBJean** [comment]
Closing this in favor of #170
